<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Consistent custom exception classes in Python | kbairak’s blog</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="Consistent custom exception classes in Python" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="This was originally published in hackernoon for Transifex." />
<meta property="og:description" content="This was originally published in hackernoon for Transifex." />
<link rel="canonical" href="https://kbairak.github.io/programming/python/2021/01/21/custom_exceptions.html" />
<meta property="og:url" content="https://kbairak.github.io/programming/python/2021/01/21/custom_exceptions.html" />
<meta property="og:site_name" content="kbairak’s blog" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2021-01-21T17:00:00+02:00" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Consistent custom exception classes in Python" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"BlogPosting","dateModified":"2021-01-21T17:00:00+02:00","datePublished":"2021-01-21T17:00:00+02:00","description":"This was originally published in hackernoon for Transifex.","headline":"Consistent custom exception classes in Python","mainEntityOfPage":{"@type":"WebPage","@id":"https://kbairak.github.io/programming/python/2021/01/21/custom_exceptions.html"},"url":"https://kbairak.github.io/programming/python/2021/01/21/custom_exceptions.html"}</script>
<!-- End Jekyll SEO tag -->
<link rel="stylesheet" href="/assets/main.css"><link type="application/atom+xml" rel="alternate" href="https://kbairak.github.io/feed.xml" title="kbairak&apos;s blog" /></head>
<body><header class="site-header" role="banner">

  <div class="wrapper"><a class="site-title" rel="author" href="/">kbairak&#39;s blog</a><nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
            </svg>
          </span>
        </label>

        <div class="trigger"><a class="page-link" href="/about/">About</a></div>
      </nav></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <article class="post h-entry" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title p-name" itemprop="name headline">Consistent custom exception classes in Python</h1>
    <p class="post-meta">
      <time class="dt-published" datetime="2021-01-21T17:00:00+02:00" itemprop="datePublished">Jan 21, 2021
      </time></p>
  </header>

  <div class="post-content e-content" itemprop="articleBody">
    <p><em>This was originally published in <a href="https://hackernoon.com/consistent-custom-exception-classes-in-python-sd153w0l">hackernoon</a> for Transifex.</em></p>

<p>Having to handle exceptions is common in Python and so is having to define your
own. Yet, I have seen competing ways of doing so in various projects. The
inconsistency comes from <code class="language-plaintext highlighter-rouge">Exception</code>s being something that can easily be
subclassed and extended, but also something that can be easily instantiated and
used in their base form.</p>

<p>Here is a common way to define custom exceptions in Python:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="bp">self</span><span class="p">.</span><span class="n">msg</span> <span class="o">=</span> <span class="n">msg</span>

<span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="s">"Something went wrong"</span><span class="p">)</span>
<span class="k">except</span> <span class="n">MyException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>        <span class="c1"># &lt;&lt;&lt; Something went wrong
</span>    <span class="k">print</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>  <span class="c1"># &lt;&lt;&lt; MyException('Something went wrong')
</span></code></pre></div></div>

<p>In general, this seems to work fine. In fact, it works “better than it should”.
<em>Somehow</em>, Python knows how to properly execute the <code class="language-plaintext highlighter-rouge">str</code> and <code class="language-plaintext highlighter-rouge">repr</code> methods,
even though we didn’t write any code for them.</p>

<p>So is there a problem with this approach? Let’s try something slightly
different:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1"># Same as before
</span><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="bp">self</span><span class="p">.</span><span class="n">msg</span> <span class="o">=</span> <span class="n">msg</span>

<span class="k">try</span><span class="p">:</span>
    <span class="c1"># Now we use a keyword argument
</span>    <span class="k">raise</span> <span class="n">MyException</span><span class="p">(</span><span class="n">msg</span><span class="o">=</span><span class="s">"Something went wrong"</span><span class="p">)</span>
<span class="k">except</span> <span class="n">MyException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>        <span class="c1"># &lt;&lt;&lt;
</span>    <span class="k">print</span><span class="p">(</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">))</span>  <span class="c1"># &lt;&lt;&lt; MyException()
</span></code></pre></div></div>

<p>Oh no! Looks like we broke the <code class="language-plaintext highlighter-rouge">str</code> and <code class="language-plaintext highlighter-rouge">repr</code> methods. How did this happen?</p>

<p>Although nothing prevents us from assigning attributes to an <code class="language-plaintext highlighter-rouge">Exception</code> object
(the <code class="language-plaintext highlighter-rouge">self.msg = msg</code> part), there is a special place in <code class="language-plaintext highlighter-rouge">Exception</code>’s heart
for the constructor’s positional arguments:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">e</span> <span class="o">=</span> <span class="nb">Exception</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>

<span class="n">e</span><span class="p">.</span><span class="n">__dict__</span>  <span class="c1"># &lt;&lt;&lt; {}
</span><span class="n">e</span><span class="p">.</span><span class="n">args</span>      <span class="c1"># &lt;&lt;&lt; (1, 2, 3)
</span><span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>      <span class="c1"># &lt;&lt;&lt; '(1, 2, 3)'
</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>     <span class="c1"># &lt;&lt;&lt; 'Exception(1, 2, 3)'
</span>
<span class="n">e</span><span class="p">.</span><span class="n">a</span> <span class="o">=</span> <span class="s">'b'</span>
<span class="n">e</span><span class="p">.</span><span class="n">__dict__</span>  <span class="c1"># &lt;&lt;&lt; {'a': 'b'}
</span><span class="n">e</span><span class="p">.</span><span class="n">args</span>      <span class="c1"># &lt;&lt;&lt; (1, 2, 3)
</span><span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>      <span class="c1"># &lt;&lt;&lt; '(1, 2, 3)'
</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>     <span class="c1"># &lt;&lt;&lt; 'Exception(1, 2, 3)'
</span></code></pre></div></div>

<p>But not so much for keyword arguments:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">e</span> <span class="o">=</span> <span class="nb">Exception</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="n">b</span><span class="o">=</span><span class="mi">2</span><span class="p">)</span>
<span class="c1"># &lt;&lt;&lt; ---------------------------------------------------------------------------
# &lt;&lt;&lt; TypeError                                 Traceback (most recent call last)
# &lt;&lt;&lt; &lt;ipython-input-9-0f7c585491d4&gt; in &lt;module&gt;
# &lt;&lt;&lt; ----&gt; 1 e = Exception(1, b=2)
# &lt;&lt;&lt;
# &lt;&lt;&lt; TypeError: Exception() takes no keyword arguments
</span></code></pre></div></div>

<p>When we defined our own <code class="language-plaintext highlighter-rouge">__init__</code> method, making it able to accept the <code class="language-plaintext highlighter-rouge">msg</code>
keyword argument, there was a difference between the resulting objects when we
passed positional arguments versus when we passed keyword arguments. In short,
the following look like they should be identical, but aren’t:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">MyException</span><span class="p">(</span><span class="s">"Something went wrong"</span><span class="p">).</span><span class="n">args</span>      <span class="c1"># &lt;&lt;&lt; ('Something went wrong',)
</span><span class="n">MyException</span><span class="p">(</span><span class="n">msg</span><span class="o">=</span><span class="s">"Something went wrong"</span><span class="p">).</span><span class="n">args</span>  <span class="c1"># &lt;&lt;&lt; ()
</span></code></pre></div></div>

<p><em>(I suspect that there is some sort of “pre-initializer” in the base
<code class="language-plaintext highlighter-rouge">Exception</code> class, possibly a <code class="language-plaintext highlighter-rouge">__new__</code> method, that captures the positional
arguments to the <code class="language-plaintext highlighter-rouge">args</code> attribute and then invokes our <code class="language-plaintext highlighter-rouge">__init__</code> method)</em></p>

<p>One thing we could do to fix this inconsistency is implement the methods we
“broke”:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="bp">self</span><span class="p">.</span><span class="n">msg</span> <span class="o">=</span> <span class="n">msg</span>

    <span class="k">def</span> <span class="nf">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">msg</span>

    <span class="k">def</span> <span class="nf">__repr__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="sa">f</span><span class="s">"MyException(</span><span class="si">{</span><span class="bp">self</span><span class="p">.</span><span class="n">msg</span><span class="si">}</span><span class="s">)"</span>

<span class="n">e</span> <span class="o">=</span> <span class="n">MyException</span><span class="p">(</span><span class="n">msg</span><span class="o">=</span><span class="s">'Something went wrong'</span><span class="p">)</span>

<span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>   <span class="c1"># &lt;&lt;&lt; 'Something went wrong'
</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>  <span class="c1"># &lt;&lt;&lt; MyException('Something went wrong')
</span></code></pre></div></div>

<p>However this is not my suggestion. First of all, it’s boring. But I also feel
like it goes against the “spirit” of how Python exceptions are supposed to be
structured. Maybe some exception handling code later on will inspect the <code class="language-plaintext highlighter-rouge">args</code>
attribute, expecting relevant information to be there.</p>

<p>What I propose is the following:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">().</span><span class="n">__init__</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span>

    <span class="o">@</span><span class="nb">property</span>
    <span class="k">def</span> <span class="nf">msg</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>
</code></pre></div></div>

<p>This way, you can initialize the exception with either positional or keyword
arguments and it will behave the same way:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">e</span> <span class="o">=</span> <span class="n">MyException</span><span class="p">(</span><span class="n">msg</span><span class="o">=</span><span class="s">'Something went wrong'</span><span class="p">)</span>

<span class="n">e</span><span class="p">.</span><span class="n">__dict__</span>  <span class="c1"># &lt;&lt;&lt; {}
</span><span class="n">e</span><span class="p">.</span><span class="n">args</span>      <span class="c1"># &lt;&lt;&lt; ('Something went wrong',)
</span><span class="n">e</span><span class="p">.</span><span class="n">msg</span>       <span class="c1"># &lt;&lt;&lt; 'Something went wrong'
</span><span class="nb">str</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>      <span class="c1"># &lt;&lt;&lt; 'Something went wrong'
</span><span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>     <span class="c1"># &lt;&lt;&lt; "MyException('Something went wrong')"
</span></code></pre></div></div>

<p>However, now you can’t change the <code class="language-plaintext highlighter-rouge">msg</code> attribute/property.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">e</span><span class="p">.</span><span class="n">msg</span> <span class="o">=</span> <span class="s">"Something else went wrong"</span>
<span class="c1"># &lt;&lt;&lt; ---------------------------------------------------------------------------
# &lt;&lt;&lt; AttributeError                            Traceback (most recent call last)
# &lt;&lt;&lt; &lt;ipython-input-29-32de7ec53be2&gt; in &lt;module&gt;
# &lt;&lt;&lt; ----&gt; 1 e.msg = "Something else went wrong"
# &lt;&lt;&lt; 
# &lt;&lt;&lt; AttributeError: can't set attribute
</span></code></pre></div></div>

<p>Generally, <strong>I don’t see why exception objects should be mutable</strong>, but if you
want them to be, I would suggest doing it through properties as well:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">().</span><span class="n">__init__</span><span class="p">(</span><span class="n">msg</span><span class="p">)</span>

    <span class="o">@</span><span class="nb">property</span>
    <span class="k">def</span> <span class="nf">msg</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span>

    <span class="o">@</span><span class="n">msg</span><span class="p">.</span><span class="n">setter</span>
    <span class="k">def</span> <span class="nf">msg</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">value</span><span class="p">):</span>
        <span class="bp">self</span><span class="p">.</span><span class="n">args</span> <span class="o">=</span> <span class="p">(</span><span class="n">value</span><span class="p">,</span> <span class="p">)</span>

<span class="n">e</span> <span class="o">=</span> <span class="n">MyException</span><span class="p">(</span><span class="n">msg</span><span class="o">=</span><span class="s">'Something went wrong'</span><span class="p">)</span>
<span class="n">e</span><span class="p">.</span><span class="n">msg</span> <span class="o">=</span> <span class="s">"Something else went wrong"</span>
<span class="nb">repr</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>  <span class="c1"># &lt;&lt;&lt; "MyException('Something else went wrong')"
</span></code></pre></div></div>

<p>With multiple (keyword) arguments, you can do:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">,</span> <span class="n">status_code</span><span class="o">=</span><span class="bp">None</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">().</span><span class="n">__init__</span><span class="p">(</span><span class="n">msg</span><span class="p">,</span> <span class="n">status_code</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">_set</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">value</span><span class="p">):</span>
        <span class="n">args</span> <span class="o">=</span> <span class="nb">list</span><span class="p">(</span><span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">)</span>
        <span class="n">args</span><span class="p">[</span><span class="n">position</span><span class="p">]</span> <span class="o">=</span> <span class="n">value</span>
        <span class="bp">self</span><span class="p">.</span><span class="n">args</span> <span class="o">=</span> <span class="nb">tuple</span><span class="p">(</span><span class="n">args</span><span class="p">)</span>

    <span class="n">msg</span> <span class="o">=</span> <span class="nb">property</span><span class="p">(</span><span class="k">lambda</span> <span class="bp">self</span><span class="p">:</span> <span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">[</span><span class="mi">0</span><span class="p">],</span>
                   <span class="k">lambda</span> <span class="bp">self</span><span class="p">,</span> <span class="n">value</span><span class="p">:</span> <span class="bp">self</span><span class="p">.</span><span class="n">_set</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="n">value</span><span class="p">))</span>
    <span class="n">status_code</span> <span class="o">=</span> <span class="nb">property</span><span class="p">(</span><span class="k">lambda</span> <span class="bp">self</span><span class="p">:</span> <span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">[</span><span class="mi">1</span><span class="p">],</span>
                           <span class="k">lambda</span> <span class="bp">self</span><span class="p">,</span> <span class="n">value</span><span class="p">:</span> <span class="bp">self</span><span class="p">.</span><span class="n">_set</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="n">value</span><span class="p">))</span>
</code></pre></div></div>

<p>This is a bit boilerplate-y but overall I think it’s worth it to ensure the
<code class="language-plaintext highlighter-rouge">Exception</code> objects remain consistent. Things can be made better with a
utility, I guess:</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1"># utils.py
</span><span class="k">def</span> <span class="nf">_set</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">value</span><span class="p">):</span>
    <span class="n">args</span> <span class="o">=</span> <span class="nb">list</span><span class="p">(</span><span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">)</span>
    <span class="n">args</span><span class="p">[</span><span class="n">position</span><span class="p">]</span> <span class="o">=</span> <span class="n">value</span>
    <span class="bp">self</span><span class="p">.</span><span class="n">args</span> <span class="o">=</span> <span class="nb">tuple</span><span class="p">(</span><span class="n">args</span><span class="p">)</span>

<span class="k">def</span> <span class="nf">exc_property</span><span class="p">(</span><span class="n">position</span><span class="p">):</span>
    <span class="k">return</span> <span class="nb">property</span><span class="p">(</span><span class="k">lambda</span> <span class="bp">self</span><span class="p">:</span> <span class="bp">self</span><span class="p">.</span><span class="n">args</span><span class="p">[</span><span class="n">position</span><span class="p">],</span>
                    <span class="k">lambda</span> <span class="bp">self</span><span class="p">,</span> <span class="n">value</span><span class="p">:</span> <span class="n">_set</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">position</span><span class="p">,</span> <span class="n">value</span><span class="p">))</span>

<span class="c1"># exceptions.py
</span><span class="kn">from</span> <span class="nn">.utils</span> <span class="kn">import</span> <span class="n">exc_property</span>

<span class="k">class</span> <span class="nc">MyException</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">msg</span><span class="p">,</span> <span class="n">status_code</span><span class="o">=</span><span class="bp">None</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">().</span><span class="n">__init__</span><span class="p">(</span><span class="n">msg</span><span class="p">,</span> <span class="n">status_code</span><span class="p">)</span>

    <span class="n">msg</span> <span class="o">=</span> <span class="n">exc_property</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
    <span class="n">status_code</span> <span class="o">=</span> <span class="n">exc_property</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
</code></pre></div></div>

<p>This way, you get the <code class="language-plaintext highlighter-rouge">str</code> and <code class="language-plaintext highlighter-rouge">repr</code> method implemented for free (you can
still override them if you want), the <code class="language-plaintext highlighter-rouge">args</code> attribute will behave the same way
regardless of whether you initialize your exception with positional or keyword
arguments and you can access attributes as if they were normal attributes set
to <code class="language-plaintext highlighter-rouge">self</code> through assignment.</p>

<p>This looks like a lot of work, but:</p>

<ol>
  <li>
    <p>As I said, exceptions generally have no reason to be mutable, so you
shouldn’t have to implement the setters</p>
  </li>
  <li>
    <p>Using the <code class="language-plaintext highlighter-rouge">exc_property</code> trick, you will only write the slightly messier
code only once, the <code class="language-plaintext highlighter-rouge">Exception</code> subclasses themselves will remain short and
sweet</p>
  </li>
</ol>


  </div><a class="u-url" href="/programming/python/2021/01/21/custom_exceptions.html" hidden></a>
</article>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/"></data>

  <div class="wrapper">

    <h2 class="footer-heading">kbairak&#39;s blog</h2>

    <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        <ul class="contact-list">
          <li class="p-name">kbairak&#39;s blog</li><li><a class="u-email" href="mailto:ikijob@gmail.com">ikijob@gmail.com</a></li></ul>
      </div>

      <div class="footer-col footer-col-2"><ul class="social-media-list"><li><a href="https://github.com/kbairak"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#github"></use></svg> <span class="username">kbairak</span></a></li><li><a href="https://www.twitter.com/kbairak"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#twitter"></use></svg> <span class="username">kbairak</span></a></li></ul>
</div>

      <div class="footer-col footer-col-3">
        <p>Mostly programming tips and tutorials, mostly in Python. But who knows? I may rumble about other things as well.</p>
      </div>
    </div>

  </div>

</footer>
</body>

</html>
